import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type TrendPoint = { compliant: number; date: string; rate: number; total: number };
type PpeBreakdown = { canonicalPpeClass: string; compliant: number; nonCompliant: number };
type SafetyDistribution = { color: string; count: number; status: string };

export function ReportCharts({ ppeBreakdown, filteredObservationCount, period, safetyDistribution, trend }: { ppeBreakdown: PpeBreakdown[]; filteredObservationCount: number; period: string; safetyDistribution: SafetyDistribution[]; trend: TrendPoint[] }) {
  return <div className="mt-8 grid gap-5 xl:grid-cols-2">
    <section aria-label="PPE Compliance trend" className="border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold text-slate-950">PPE Compliance trend</h2><p className="mt-1 text-sm text-slate-600">The line shows the compliance percentage; bars show observations per day.</p><div aria-hidden="true" className="mt-5 h-64"><ResponsiveContainer height="100%" width="100%"><ComposedChart data={trend}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis domain={[0, 100]} unit="%" /><Tooltip /><Legend /><Bar dataKey="total" fill="#cbd5e1" isAnimationActive={false} name="Observations" /><Line dataKey="rate" isAnimationActive={false} name="Compliance" stroke="#047857" strokeWidth={2} type="monotone" /></ComposedChart></ResponsiveContainer></div><p className="mt-4 font-mono text-xs text-slate-600">Period: {period} · {filteredObservationCount} PPE Compliance observations</p></section>
    <section aria-label="Canonical PPE Classes breakdown" className="border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold text-slate-950">Canonical PPE Classes breakdown</h2><p className="mt-1 text-sm text-slate-600">Compare compliant and non-compliant observations for each Canonical PPE Class.</p><div aria-hidden="true" className="mt-5 h-64"><ResponsiveContainer height="100%" width="100%"><BarChart data={ppeBreakdown}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" /><XAxis dataKey="canonicalPpeClass" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} /><Tooltip /><Legend /><Bar dataKey="compliant" fill="#047857" isAnimationActive={false} name="Compliant" /><Bar dataKey="nonCompliant" fill="#b91c1c" isAnimationActive={false} name="Non-compliant" /></BarChart></ResponsiveContainer></div><p className="mt-4 text-sm text-slate-600">{ppeBreakdown.map((item) => `${item.canonicalPpeClass}: ${item.compliant} compliant, ${item.nonCompliant} non-compliant`).join(" · ")}</p></section>
    <section aria-label="Safety status distribution" className="border border-slate-200 bg-white p-5 xl:col-span-2"><h2 className="text-lg font-semibold text-slate-950">Safety status distribution</h2><p className="mt-1 text-sm text-slate-600">Safe, Warning, and Critical are derived from the Employees' Safety Scores in the selected observations.</p><div aria-hidden="true" className="mt-5 h-56"><ResponsiveContainer height="100%" width="100%"><BarChart data={safetyDistribution} layout="vertical"><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" /><XAxis allowDecimals={false} type="number" /><YAxis dataKey="status" type="category" width={80} /><Tooltip /><Bar dataKey="count" isAnimationActive={false} name="Employee" radius={[0, 3, 3, 0]}>{safetyDistribution.map((item) => <Cell fill={item.color} key={item.status} />)}</Bar></BarChart></ResponsiveContainer></div><p className="mt-4 text-sm text-slate-600">{safetyDistribution.map((item) => `${item.status}: ${item.count}`).join(" · ")}</p></section>
  </div>;
}
